sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - ELM_VERSION=0.18.0 COVERALLS_REPO_TOKEN=qPx1suoyo7HD8uotEhbOrfuk1EJYcOo0N

language: node_js

cache:
  yarn: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules
    - test/tasks/tmp/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  - if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - nvm install
  - yarn global add elm@$ELM_VERSION
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - yarn

after_success:
  yarn run coverage
